/**
 * Pre-seeded high quality verification quizzes per skill
 */
const quizBank = {
  sql_mastery: {
    skill_name: "SQL & Data Warehousing",
    questions: [
      {
        id: 1,
        question: "What is the key difference between RANK() and DENSE_RANK() window functions in SQL?",
        options: [
          "RANK() assigns consecutive numbers with no gaps, whereas DENSE_RANK() skips numbers on ties.",
          "RANK() skips rank numbers after a tie (e.g. 1, 2, 2, 4), whereas DENSE_RANK() does not skip rank numbers (e.g. 1, 2, 2, 3).",
          "DENSE_RANK() can only be used with numeric columns, while RANK() works on text.",
          "There is no difference; they are aliases for the same function."
        ],
        correct_index: 1,
        explanation: "RANK() skips values when there are duplicates (ties), creating gaps in the numbering sequence. DENSE_RANK() maintains strict consecutive integers."
      },
      {
        id: 2,
        question: "When optimizing a large analytical query on a partitioned table in BigQuery/Snowflake, which strategy prevents full table scans?",
        options: [
          "Always converting string columns into JSON payloads",
          "Filtering on the partition key column in the WHERE clause (partition pruning)",
          "Replacing JOIN clauses with subqueries",
          "Increasing the query timeout setting"
        ],
        correct_index: 1,
        explanation: "Partition pruning allows the database engine to scan only the partition files matching your WHERE filter criteria, reducing scanned bytes and execution time dramatically."
      },
      {
        id: 3,
        question: "Which SQL clause is used to filter aggregated results generated by a GROUP BY clause?",
        options: [
          "WHERE",
          "HAVING",
          "QUALIFY",
          "OVER"
        ],
        correct_index: 1,
        explanation: "The HAVING clause filters aggregated groups after GROUP BY, whereas WHERE filters individual rows before grouping occurs."
      }
    ]
  },
  python_analytics: {
    skill_name: "Python for Data & Automation",
    questions: [
      {
        id: 1,
        question: "Why is vectorized computation with Pandas/NumPy significantly faster than using standard Python for-loops over a DataFrame?",
        options: [
          "Vectorization converts all numbers to integers before processing.",
          "Vectorized operations use pre-compiled C-level loops and contiguous memory blocks, avoiding Python interpreter overhead per row.",
          "Pandas automatically runs all Python loops in parallel web workers.",
          "For-loops in Python double the memory overhead per iteration."
        ],
        correct_index: 1,
        explanation: "Vectorization delegates calculations to optimized C/Fortran libraries without interpreter loop overhead."
      },
      {
        id: 2,
        question: "Which Pandas method is best suited for combining two DataFrames based on a shared key column?",
        options: [
          "pd.concat()",
          "df.append()",
          "pd.merge()",
          "df.combine_first()"
        ],
        correct_index: 2,
        explanation: "pd.merge() performs SQL-like database joins (INNER, LEFT, RIGHT, OUTER) on designated key columns."
      },
      {
        id: 3,
        question: "In Python API automation, what is the purpose of checking response.raise_for_status() when using the requests library?",
        options: [
          "It forces the API to send data in XML format.",
          "It raises an HTTPError exception if the HTTP request returned an unsuccessful status code (4xx or 5xx).",
          "It automatically encrypts the API response payload.",
          "It retries the API request 5 times synchronously."
        ],
        correct_index: 1,
        explanation: "response.raise_for_status() ensures network or client/server error codes cause an immediate exception rather than silently proceeding with bad data."
      }
    ]
  },
  tableau_bi: {
    skill_name: "BI & Data Visualization (Tableau/PowerBI)",
    questions: [
      {
        id: 1,
        question: "In Tableau, what does a FIXED Level of Detail (LOD) expression like {FIXED [Region] : SUM([Sales])} accomplish?",
        options: [
          "It fixes the chart color palette to a specific gradient.",
          "It calculates the total sales per Region regardless of any other dimension filters applied to the view.",
          "It filters out all regions except the first one in alphabetical order.",
          "It creates an immutable database view on the server."
        ],
        correct_index: 1,
        explanation: "FIXED LOD expressions compute aggregates using specified dimensions without reference to the dimensions present in the visualization view."
      },
      {
        id: 2,
        question: "Which visualization type is most effective for displaying correlation between two continuous numeric variables?",
        options: [
          "Bar Chart",
          "Scatter Plot",
          "Pie Chart",
          "Treemap"
        ],
        correct_index: 1,
        explanation: "Scatter plots map two continuous variables along X and Y axes, making patterns, clusters, and correlations instantly recognizable."
      },
      {
        id: 3,
        question: "What is a primary principle of executive dashboard design accessibility?",
        options: [
          "Using as many bright primary colors as possible to catch attention.",
          "Maintaining clear visual hierarchy, consistent color semantics (e.g. green/red for metrics), and high contrast.",
          "Including 10+ detailed tables on a single screen.",
          "Hiding key summary KPIs inside collapsible dropdowns."
        ],
        correct_index: 1,
        explanation: "High-contrast visual hierarchy and predictable color semantics ensure key metrics can be understood at a glance by executive stakeholders."
      }
    ]
  },
  stat_modeling: {
    skill_name: "Statistical Modeling & A/B Testing",
    questions: [
      {
        id: 1,
        question: "What does a p-value of 0.03 indicate in an A/B test with a significance threshold (alpha) set to 0.05?",
        options: [
          "There is a 3% probability that the variant is worse than control.",
          "Assuming the null hypothesis is true, there is a 3% chance of observing a result at least as extreme. Since 0.03 < 0.05, we reject the null hypothesis.",
          "The variant increased conversion rate by exactly 3%.",
          "The test requires 3% more sample size to reach statistical power."
        ],
        correct_index: 1,
        explanation: "A p-value below alpha (0.05) means the observed difference is statistically significant, making chance an unlikely explanation."
      },
      {
        id: 2,
        question: "What is 'p-hacking' (or data dredging) in statistical experiment analysis?",
        options: [
          "Hacking into database servers to alter test results.",
          "Repeatedly testing multiple sub-groups or stopping an experiment early without adjusting p-value thresholds until a statistically significant result appears by chance.",
          "Calculating confidence intervals using median instead of mean.",
          "Running A/B tests on mobile devices only."
        ],
        correct_index: 1,
        explanation: "P-hacking inflates Type I false positive rates by selectively analyzing slice combinations until a random fluctuation looks statistically significant."
      },
      {
        id: 3,
        question: "What is statistical power in an experiment design?",
        options: [
          "The speed at which the server renders the experiment page.",
          "The probability of correctly rejecting a false null hypothesis (detecting a real effect if one exists). Typically targeted at 80%+.",
          "The total number of servers running the experiment.",
          "The percentage of users assigned to the control group."
        ],
        correct_index: 1,
        explanation: "Statistical power (1 - beta) ensures your test sample size is large enough to reliably detect true differences between treatment and control."
      }
    ]
  },
  llm_engineering: {
    skill_name: "LLM & RAG Application Building",
    questions: [
      {
        id: 1,
        question: "In a Retrieval-Augmented Generation (RAG) architecture, what is the primary role of a Vector Database?",
        options: [
          "To host the LLM weights on a GPU cluster.",
          "To store text chunk embeddings and perform fast semantic similarity search (e.g. cosine distance) to retrieve relevant context.",
          "To convert SQL databases into JSON web tokens.",
          "To compress prompt tokens before sending them to the API."
        ],
        correct_index: 1,
        explanation: "Vector DBs index high-dimensional vector embeddings so similarity searches return context chunks relevant to the user query."
      },
      {
        id: 2,
        question: "Why is chunk size and chunk overlap tuning crucial for effective RAG retrieval?",
        options: [
          "Because larger chunks make the API response print faster.",
          "Too large chunks introduce noise and exceed LLM context windows, while too small chunks lose context; overlap prevents splitting key statements across boundaries.",
          "Chunk overlap is required by law for data privacy compliance.",
          "Vector databases reject documents if chunk size is under 1,000 words."
        ],
        correct_index: 1,
        explanation: "Optimal chunking balances semantic coherence with retrieval precision while overlap ensures concepts split near boundaries are preserved."
      },
      {
        id: 3,
        question: "What is an LLM Agent in software architecture?",
        options: [
          "A customer support representative using a chat interface.",
          "An autonomous system combining an LLM controller, memory, planning tools, and execution tools (e.g. web search, API execution) to solve multi-step goals.",
          "A background daemon that cleans up temporary log files.",
          "A hardcoded set of nested IF-ELSE statements."
        ],
        correct_index: 1,
        explanation: "Agents use LLM reasoning to dynamically decide which tools to invoke, evaluate feedback, and iterate toward a complex objective."
      }
    ]
  }
};

/**
 * Returns verification quiz for a given skill_id
 */
export function getQuizForSkill(skillId) {
  if (quizBank[skillId]) {
    return quizBank[skillId];
  }

  // Fallback dynamic quiz template
  const readableName = skillId.replace(/_/g, ' ').toUpperCase();
  return {
    skill_name: readableName,
    questions: [
      {
        id: 1,
        question: `What is a primary best practice when applying ${readableName} in an enterprise production environment?`,
        options: [
          "Writing clear, documented modular code with comprehensive error handling and logging",
          "Disabling automated testing to deploy faster",
          "Hardcoding configuration credentials directly into source files",
          "Avoiding version control"
        ],
        correct_index: 0,
        explanation: "Modular, documented, and resilient implementation is essential for enterprise scalability."
      },
      {
        id: 2,
        question: `How does mastering ${readableName} directly advance a candidate's readiness for senior roles?`,
        options: [
          "It reduces system design review meetings",
          "It equips professionals to solve complex technical bottlenecks and mentor junior team members",
          "It eliminates the need for cross-team collaboration",
          "It allows engineers to skip code reviews"
        ],
        correct_index: 1,
        explanation: "Senior technical roles require both deep domain troubleshooting capabilities and team leadership."
      },
      {
        id: 3,
        question: `Which metric is most critical for evaluating performance in ${readableName}?`,
        options: [
          "Lines of code written per day",
          "System throughput, latency, accuracy, and maintainability",
          "Number of open browser tabs",
          "Font size used in code editor"
        ],
        correct_index: 1,
        explanation: "Real-world engineering quality is judged by system efficiency, correctness, and maintainability."
      }
    ]
  };
}
